"""add session_string to telegramaccount

Revision ID: 3926f0fe0afb
Revises: 98b7e780df0a
Create Date: 2025-12-23 19:36:26.820894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3926f0fe0afb'
down_revision: Union[str, Sequence[str], None] = '98b7e780df0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegramaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_string', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegramaccount', schema=None) as batch_op:
        batch_op.drop_column('session_string')

    # ### end Alembic commands ###
