"""add seniority to vacancy review

Revision ID: 5e679ce300d1
Revises: 8ec5b1633c10
Create Date: 2025-12-26 12:43:09.469131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e679ce300d1'
down_revision: Union[str, Sequence[str], None] = '8ec5b1633c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancyreview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seniority', sa.Enum('TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', name='seniority'), nullable=True))
        batch_op.create_index(batch_op.f('ix_vacancyreview_seniority'), ['seniority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancyreview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancyreview_seniority'))
        batch_op.drop_column('seniority')

    # ### end Alembic commands ###
