"""Remove folder_id from Dialog

Revision ID: 7a6996e9afb6
Revises: dd6ec247f83e
Create Date: 2025-12-22 09:37:15.508385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a6996e9afb6'
down_revision: Union[str, Sequence[str], None] = 'dd6ec247f83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialog', schema=None) as batch_op:
        batch_op.drop_column('folder_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
