"""initial

Revision ID: 98b7e780df0a
Revises:
Create Date: 2025-12-22 10:47:31.831498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "98b7e780df0a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("role", sa.Enum("ADMIN", "USER", name="userrole"), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("sso_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("sso_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  with op.batch_alter_table("user", schema=None) as batch_op:
    batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

  op.create_table(
    "folder",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["user.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  with op.batch_alter_table("folder", schema=None) as batch_op:
    batch_op.create_index(batch_op.f("ix_folder_name"), ["name"], unique=False)

  op.create_table(
    "telegramaccount",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("api_id", sa.Integer(), nullable=False),
    sa.Column("api_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["user.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "dialog",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("account_id", sa.Integer(), nullable=False),
    sa.Column(
      "entity_type",
      sa.Enum("USER", "GROUP", "CHANNEL", name="dialogtype"),
      nullable=False,
    ),
    sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(
      ["account_id"],
      ["telegramaccount.id"],
    ),
    sa.PrimaryKeyConstraint("id", "account_id"),
  )
  with op.batch_alter_table("dialog", schema=None) as batch_op:
    batch_op.create_index(batch_op.f("ix_dialog_name"), ["name"], unique=False)
    batch_op.create_index(batch_op.f("ix_dialog_username"), ["username"], unique=False)

  op.create_table(
    "dialogfolderlink",
    sa.Column("dialog_id", sa.Integer(), nullable=False),
    sa.Column("account_id", sa.Integer(), nullable=False),
    sa.Column("folder_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
      ["dialog_id", "account_id"],
      ["dialog.id", "dialog.account_id"],
    ),
    sa.ForeignKeyConstraint(
      ["folder_id"],
      ["folder.id"],
    ),
    sa.PrimaryKeyConstraint("dialog_id", "account_id", "folder_id"),
  )
  op.create_table(
    "message",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("dialog_id", sa.Integer(), nullable=False),
    sa.Column("account_id", sa.Integer(), nullable=False),
    sa.Column("from_id", sa.Integer(), nullable=True),
    sa.Column(
      "from_type", sa.Enum("USER", "CHAT", "CHANNEL", name="peertype"), nullable=True
    ),
    sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("date", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["dialog_id", "account_id"],
      ["dialog.id", "dialog.account_id"],
    ),
    sa.PrimaryKeyConstraint("id", "dialog_id", "account_id"),
  )
  op.create_table(
    "vacancyreview",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("message_id", sa.Integer(), nullable=False),
    sa.Column("dialog_id", sa.Integer(), nullable=False),
    sa.Column("account_id", sa.Integer(), nullable=False),
    sa.Column(
      "decision",
      sa.Enum("DISMISS", "APPROVE", name="vacancyreviewdecision"),
      nullable=False,
    ),
    sa.Column("contacts", sa.JSON(), nullable=True),
    sa.Column("vacancy_position", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
      "vacancy_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
    ),
    sa.Column(
      "vacancy_requirements", sqlmodel.sql.sqltypes.AutoString(), nullable=True
    ),
    sa.Column("salary_fork_from", sa.Integer(), nullable=True),
    sa.Column("salary_fork_to", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(
      ["message_id", "dialog_id", "account_id"],
      ["message.id", "message.dialog_id", "message.account_id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "vacancyprogress",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("review_id", sa.Integer(), nullable=False),
    sa.Column(
      "status",
      sa.Enum(
        "NEW",
        "CONTACT",
        "IGNORE",
        "INTERVIEW",
        "REJECT",
        "OFFER",
        name="vacancyprogressstatus",
      ),
      nullable=False,
    ),
    sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(
      ["review_id"],
      ["vacancyreview.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("review_id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("vacancyprogress")
  op.drop_table("vacancyreview")
  op.drop_table("message")
  op.drop_table("dialogfolderlink")
  with op.batch_alter_table("dialog", schema=None) as batch_op:
    batch_op.drop_index(batch_op.f("ix_dialog_username"))
    batch_op.drop_index(batch_op.f("ix_dialog_name"))

  op.drop_table("dialog")
  op.drop_table("telegramaccount")
  with op.batch_alter_table("folder", schema=None) as batch_op:
    batch_op.drop_index(batch_op.f("ix_folder_name"))

  op.drop_table("folder")
  with op.batch_alter_table("user", schema=None) as batch_op:
    batch_op.drop_index(batch_op.f("ix_user_email"))

  op.drop_table("user")
  # ### end Alembic commands ###
