"""add experience to vacancy review

Revision ID: bca40a59e473
Revises: 4f922d812f37
Create Date: 2025-12-26 22:54:04.648721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bca40a59e473"
down_revision: Union[str, Sequence[str], None] = "4f922d812f37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table("vacancyreview", schema=None) as batch_op:
    batch_op.add_column(sa.Column("experience", sa.JSON(), nullable=True))

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table("vacancyreview", schema=None) as batch_op:
    batch_op.drop_column("experience")

  # ### end Alembic commands ###
