"""Add Folder model and many-to-many relationship

Revision ID: dd6ec247f83e
Revises: 43ad5c9b6219
Create Date: 2025-12-22 09:30:17.849118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dd6ec247f83e"
down_revision: Union[str, Sequence[str], None] = "43ad5c9b6219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "folder",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sqlmodel.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  with op.batch_alter_table("folder", schema=None) as batch_op:
    batch_op.create_index(batch_op.f("ix_folder_name"), ["name"], unique=False)

  op.create_table(
    "dialogfolderlink",
    sa.Column("dialog_id", sa.Integer(), nullable=False),
    sa.Column("folder_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
      ["dialog_id"],
      ["dialog.id"],
    ),
    sa.ForeignKeyConstraint(
      ["folder_id"],
      ["folder.id"],
    ),
    sa.PrimaryKeyConstraint("dialog_id", "folder_id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("dialogfolderlink")
  with op.batch_alter_table("folder", schema=None) as batch_op:
    batch_op.drop_index(batch_op.f("ix_folder_name"))

  op.drop_table("folder")
  # ### end Alembic commands ###
